stages:
    - build
    - deploy


composer:
  stage: build
  image: lorisleiva/laravel-docker:latest
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always



deploy:
  stage: deploy
  image: tiangolo/docker-with-compose
  tags:
    - v2
  services:
    - docker:dind
  script:
    - docker-compose build
    - docker-compose down
    - docker-compose up -d --force-recreate
