stages:
    - build
    - test
    - deploy


composer:
  stage: build
  only:
    - main
  tags:
    - dev
  image: lorisleiva/laravel-docker:latest
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.prod.example .env
    - php artisan key:generate
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always

phpunit:
  stage: test
  only:
    - main
  tags:
    - dev
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never

codestyle:
  stage: test
  only:
    - main
  tags:
    - dev
  dependencies: []
  script:
    - phpcs --standard=PSR12 --extensions=php app/Http/Controllers/AppController.php
