stages:
    - build
    - test
    - deploy

composer:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never

codestyle:
  stage: test
  dependencies: []
  script:
    - phpcs --standard=PSR12 --extensions=php app/Http/Controllers/AppController.php

deploy:
  stage: deploy
  image: tiangolo/docker-with-compose
  services:
    - docker:dind
  dependencies:
    - composer
  script:
    - docker-compose up -d --build
