stages:
    - build
    - deploy

build:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/


deploy:
  stage: deploy
  dependencies:
    - build
  image: tiangolo/docker-with-compose:latest
  script:
    - docker-compose up -d
