version: "3.8"

services:

  # App
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/application
    networks:
      - laravel

  # Webserver
  nginx:
    image: nginx:1.19.4-alpine
    ports:
      - 8000:80
    volumes:
      - .:/application
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel


networks:
  laravel:
    driver: bridge
