version: "3.8"

services:

  app:
    build:
      args:
        user: haakon
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravelapp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Webserver
  nginx:
    image: nginx:1.19.4-alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
