version: "3.8"

services:

  # App
  app:
    image: webdevops/php-nginx:8.0
    container_name: laravel
    working_dir: /var/www
    volumes:
      - .:/var/www/
      - ./nginx:/etc/nginx/conf.d
    ports:
    - 8000:80
