version: "3.8"

services:

  # App
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/
    networks:
      - bridge

  # Webserver
  nginx:
    image: nginx:1.19.8-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www/
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8000:80
    networks:
      - bridge

  composer:
    image: composer:2.0.7
    command: composer install --no-dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
