version: "3.7"

services:

  # App
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/
    networks:
      - bridge

  # Webserver
  nginx:
    image: nginx:1.19.4-alpine
    working_dir: /var/www
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8000:80
    networks:
      - bridge


networks:
  bridge:
    driver: bridge
