version: "3.8"

services:

  # App
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - bridge

  # Webserver
  nginx:
    image: nginx:1.19.4-alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - bridge

  composer:
    image: composer:2.0.7
    command: composer install
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - bridge


networks:
  bridge:
    driver: bridge
